image: docker:20.10.7

options:
  docker: true

pipelines:
  default:
    - step:
        name: Build and Test
        services:
          - docker
        caches:
          - dotnetcore
        script:
          - apk add --no-cache docker-compose
          - docker version
          - dotnet restore
          - dotnet build --configuration Release
          - dotnet test --configuration Release

    - step:
        name: Build Docker Image
        services:
          - docker
        script:
          - docker build -t your-dockerhub-username/your-image-name:your-tag .
          - echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin
          - docker push $DOCKER_USERNAME/hotelbook:api

definitions:
  services:
    docker:
      image: docker:20.10.7-dind

  caches:
    dotnetcore: ~/.nuget/packages