image: docker:20.10.7

options:
  docker: true

pipelines:
  default:
    - step:
        name: Build and Test
        caches:
          - dotnetcore
        services:
          - docker
        script:
          - apk add --no-cache docker-cli-compose
          - docker info
          - dotnet restore
          - dotnet build --configuration Release
          - dotnet test --configuration Release

    - step:
        name: Build Docker Image
        caches:
          - dotnetcore
        services:
          - docker
        script:
          - docker build -t your-dockerhub-username/your-image-name:your-tag .
          - echo $DOCKER_PASSWORD | docker login -u $DOCKER_USER_NAME --password-stdin
          - docker push $DOCKER_USER_NAME/$IMAGE_NAME:$TAG

definitions:
  services:
    docker:
      image: docker:20.10.7-dind

  caches:
    dotnetcore: ~/.nuget/packages